### PR TITLE
Adding support for bind mount volume types

### LINKED ISSUE #172: Missing support for bind_mount style service volumes
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[Slack Community](https://slack.cloudposse.com)

## Describe the Feature

There is support for `docker_volumes`, `fsx_volumes`, and `efs_volumes`, but there is also a 4th default type called `bind mount` in ECS. 

## Describe Ideal Solution

Adding a variable called `bind_mount_volumes`, having it just be a list of objects with `host_path` and `name`, and concatting it with the `volumes` local variable should enable this functionality.

## Additional Context

image

### PR DESCRIPTION
**Pull request by bfox1793**
## what
* Adding support for a basic bind_mount volume type for tasks

## why
* [This is a supported feature of ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html). This update adds that support into the terraform module

## references
* closes #172

### CODE REVIEW

**Comment by nitrocode** [comment]
@bfox1793 please run `make pr/auto-format` locally 😄

**Comment by bfox1793** [comment]
> @bfox1793 please run `make pr/auto-format` locally 😄

Hmm, still running into some problems locally. Could the fact that I'm running on an arm machine be the root-cause?

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

** GitHub workflows update started **


** GitHub workflows updated **

main.tf
Using gomplate from /host/build-harness/vendor/gomplate
Using terraform-docs from /host/build-harness/vendor/terraform-docs
/bin/bash: line 1: /host/build-harness/vendor/terraform-docs: cannot execute binary file: Exec format error
make: *** [/host/build-harness/modules/docs/Makefile:21: docs/terraform.md] Error 126
make: *** [build-harness/runner] Error 2
```

**Comment by nitrocode** [comment]
Hmmm. It's possible that it's failing due to arm. You could try to debug it by passing in `make -n pr/auto-format` and attempting to run the `docker` command directly.

You could also try to PR this in from a personal fork rather than a github org fork. That would probably let the cloudposse-bot commit the changes directly to the branch.

**Comment by Nuru** [comment]
@bfox1793 wrote:

> Hmm, still running into some problems locally. Could the fact that I'm running on an arm machine be the root-cause?

Perhaps, but it should not. Granted, we do not currently consider M1 supported, although it should mostly work via emulation. What is concerning here are these lines:

```
Using gomplate from /host/build-harness/vendor/gomplate
Using terraform-docs from /host/build-harness/vendor/terraform-docs
```

This means it is trying to run tools from the host file system, not the container. Our build harness will install the required tools, but we have not sorted out how to deal with the M1 vs Intel issue when doing so. In any case, that code is outdated, it should be using the tools in the container. 

I suggest you try running:

```bash
make clean
make init
make pr/auto-format
```

If you still have problems, please paste the full output from `make pr/auto-format`.

**Comment by bfox1793** [comment]
> @bfox1793 wrote:
> 
> > Hmm, still running into some problems locally. Could the fact that I'm running on an arm machine be the root-cause?
> 
> Perhaps, but it should not. Granted, we do not currently consider M1 supported, although it should mostly work via emulation. What is concerning here are these lines:
> 
> ```
> Using gomplate from /host/build-harness/vendor/gomplate
> Using terraform-docs from /host/build-harness/vendor/terraform-docs
> ```
> 
> This means it is trying to run tools from the host file system, not the container. Our build harness will install the required tools, but we have not sorted out how to deal with the M1 vs Intel issue when doing so. In any case, that code is outdated, it should be using the tools in the container.
> 
> I suggest you try running:
> 
> ```shell
> make clean
> make init
> make pr/auto-format
> ```
> 
> If you still have problems, please paste the full output from `make pr/auto-format`.

Seems the `make clean` and running through the steps again worked! README is updated.

**Review by nitrocode — APPROVED** [review]

**Comment by nitrocode** [comment]
Thank you @bfox1793 !

**Pull request merged**
