### PR TITLE
feat: support ECS service connect

### PR DESCRIPTION
**Pull request by gberenice**
## what

- This adds support for [ECS Service connect](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-connect.html), which is already supported by the provider, see [service_connect_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#service_connect_configuration) block.

## why

- Extend the module's functionality.

## references

- There is a PR that partially covers this feature, but unfortunately, it's not active for a while, and there are requested changes to be done: https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/208

### CODE REVIEW

**Review by Gowiem — DISMISSED** [review]
LGTM 💯

**Review by Benbentwo — APPROVED** [review]
LGTM 🚀

**Pull request merged**
