### PR TITLE
Add task_exec and task role policy attachments

### PR DESCRIPTION
**Pull request by sodre**
## what
* Creates two variables to accept a list of policies to attach to the generated task and task execution roles
* The policies are only attached if the the roles were created by this module.

## why
* When creating services that reference outside secrets it would be easier to pass the required policy during service creation.

## references
* This is related to #67 and #68
* Supersedes and closes #86

### CODE REVIEW

**Comment by joe-niland** [comment]
@sodre the title starts with WIP. Ready to review?

**Comment by sodre** [comment]
@joe-niland, this should be read for review.

**Review by Nuru — APPROVED** [review]

**Pull request merged**
