### PR TITLE
Add option to trigger a redeployment on apply

### PR DESCRIPTION
**Pull request by joe-niland**
## what
* Adds a variable to enable/disable triggering a new ECS service deployment on apply.

## why
* In aws provider [v4.40.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.40.0) an option was added to allow triggering a new ECS service deployment on apply.
* This is useful so the service can be updated to the latest service/task configuration without needing to take additional steps are applying the Terraform config.

## references
* None

### CODE REVIEW

**Review by jamengual — APPROVED** [review]

**Comment by jamengual** [comment]
@joe-niland you need to change your personal repo permissions so autoformat can push to the fork.

**Comment by joe-niland** [comment]
Hey @jamengual thanks for approving.
I think the Auto Format error is something different: https://sweetops.slack.com/archives/G014YEKDH4K/p1676243737035749?thread_ts=1676238918.596959&cid=G014YEKDH4K

image

**Comment by jamengual** [comment]
ohhh I c ok, so we will have to wait

**Comment by joe-niland** [comment]
Also not sure why bats is failing. Here it is from local:

image

**Comment by joe-niland** [comment]
I also realised why bats was failing. I made the min Terraform version 0.14 and it seems ok locally:

image

**Pull request merged**
