### PR TITLE
Correct type definition for `efs_volumes` and `docker_volumes` vars

### PR DESCRIPTION
**Pull request by alexstophel**
## what
* Update child attribute volume_configuration to `efs_volume_configuration` and `docker_volume_configuration`

## why
* In `main.tf` when iterating over the volumes it is looking for `efs_volume_configuration` and `docker_volume_configuration` instead of just `volume_configuration`.
** Without this change, configuration is always omitted.

## references
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/main.tf#L103
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/main.tf#L92

### CODE REVIEW

**Review by mbroers — APPROVED** [review]
if this is working locally looks good to me!

**Comment by nitrocode** [comment]
Looks like this reverts PR https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/159

@bradj @Gowiem can you folks weigh in on this?

@alexstophel could you show the exact hcl used and the error you see with the latest version? perhaps using the previous version [v0.61.0](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/releases/tag/0.61.0) may unblock you for now

**Comment by nitrocode** [comment]
This addition looks correct to me since it matches whats in the resource definition for volumes

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#volume

The more I look at this, the more it seems like we should revert PR https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/159

**Review by nitrocode — APPROVED** [review]
approved for now

**Comment by bradj** [comment]
Good catch! lgtm

**Pull request merged**
