### PR TITLE
Fix breaking changes introduced in v0.67.1

### PR DESCRIPTION
**Pull request by MaxymVlasov**
## what

Fix breaking changes introduced in #194 for `task_policy_arns` and `task_exec_policy_arns`
/cc @joe-niland 
## why

image

## references

Replacement for #195

## How to test

Use #191 test code

## Need extra testing

I didn't check how the introduced logic would work with applied stuff. 

I mean, apply #191 code, and then check what will be in the next `terraform plan`

I hope all be fine, but, in theory, it could try to recreate resources from "count" to "for_each" naming style. So additional testing is needed

### CODE REVIEW

**Comment by MaxymVlasov** [comment]
>test/bats — Tests failed 
> Cloud Posse requires all providers to be pinned with ">=" constraints and only ">=" constraints

I don't think that is good idea for this provider, but okay

**Review by Nuru — CHANGES_REQUESTED** [review]
This kind of solution warrants a broader discussion and more investigation, because it is yet another workaround for wanting to have stability of plans/resources while still handling values unknown at plan time. I could be convinced that this is a path to go, but I would want to do a lot more testing before using it here.

Our current best solution is to allow people to supply either a map with labels known at plan time or a list whose length is known at plan time. This gives users control for the case when, in this example, the ARNs are not known at plan time, but perhaps keys for the ARNs can be known. For example, one ARN per region so the keys can be regions.

**Comment by MaxymVlasov** [comment]
>Our current best solution is to allow people to supply either a map with labels known at plan time or a list whose length is known at plan time.

The second one is deprecated right now
https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/c9f96f174bcaad4363f9bca8f2573895094e2d6e/variables-deprecated.tf#L1-L11


In case you miss Slack disscutionб let me copy this:

> ...perform additional testing mentioned in the description, adjust Terratest tests and, evaluate the proposed in [pull/196](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/196) solution, because it is weird. Would be nice if a simpler solution could exists.
Otherwise, you should deal with what issue you prefer to exist:
[issues/167](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/167) or [issues/191](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/191)
In PR 196, issue 167 exist only for cases described in 191 - because Terraform can't work in different way

**Comment by MaxymVlasov** [comment]
Also,
>Our current best solution 

contains https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/167

@Nuru

**Comment by Nuru** [comment]
@MaxymVlasov 
> Otherwise, you should deal with what issue you prefer to exist: #167 or #191

Yes, our current best solution allows the module user to choose between those two problems. This proposed solution tries to automatically choose one of those solutions or the other. However, it does not give the user the option (which our best solution does) of introducing a static set of labels for the dynamic values, so that the labels can be known at plan time and be stably associated with dynamic values. 

As for the list inputs being deprecated, I believe that was a mistake and I would restore them to fully supported status.

**Comment by MaxymVlasov** [comment]
Would be nice to have some breaking change tests, but without TF apply its could be difficult, not sure how it could be done now.
But if they were to exist, 0.67.1 will be not released at all, at least, as 0.67.1

**Comment by osterman** [comment]
We have discussed this internally and @Nuru is going to take a pass at resolving this in a manner that does not rely on the untrusted provider. We have concerns about introducing that provider in our public modules.

**Pull request closed without merging**
