### PR TITLE
Flag to enable icmp rule

### PR DESCRIPTION
**Pull request by nitrocode**
## what
Enable or disable the icmp rule on the security group using a flag

## why
You may not need icmp so this will give you the option to enable or disable it

Should this  remain enabled by default ?

## references
https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/54

@aknysh

### CODE REVIEW

**Comment by nitrocode** [comment]
So the only rule on this security group is the icmp rule so if that is not needed, then the security group itself is no needed either, no ?

**Comment by Gowiem** [comment]
@nitrocode Just seeing you comment regarding if the SG is needed if ICMP is disabled: I think keeping the SG is still valid. 

I find myself using output SG IDs from modules and applying additional rules to them a lot depending on my application's needs, so I think it's still a good call to keep it.

**Comment by Gowiem** [comment]
@nitrocode Shipped as [0.29.0](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/releases/tag/0.29.0)! 👍

**Pull request merged**
