### PR TITLE
Use context.tf and latest null-label module

### PR DESCRIPTION
**Pull request by okgolove**
Update example

## what
* Use context feature and latest null-label module

## why
* The module should have context feature due to it is used by another modules like ecs-web-app

### CODE REVIEW

**Comment by joe-niland** [comment]
@okgolove thanks for this PR!

Curious about why local.enabled is used.

**Comment by okgolove** [comment]
@joe-niland I used vpc and dynamic-subnets as an example.
https://github.com/cloudposse/terraform-aws-vpc/blob/master/main.tf#L2

In my opinion it may be useful in case of we want to add additional condition.
What do you think?

**Comment by joe-niland** [comment]
Ah I see.

Yes, if another condition was added, it's good to define it in on place.

Can't see an issue in doing it this way.

**Review by joe-niland — APPROVED** [review]

**Comment by joe-niland** [comment]
Thanks very much @okgolove

**Pull request merged**
