### PR TITLE
fix external task definition must exist before first run

### PR DESCRIPTION
**Pull request by mightyguava**
## what

Change external task definition to a `list(string)` so that it can be flagged on without needing the task definition to already exist.

## why

Fix this issue when using an external task definition
```
│   49:   count                    = local.enabled && var.task_definition == null ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.
```

## references

Similar to how this was solved for the task role arn https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/main/variables.tf#L216-L226. The workaround for now is to use `-target` like mentioned in #123.

### CODE REVIEW

**Comment by goruha** [comment]
Hello @mightyguava.

Thanks for your contribution. 

Could you pls fix the following issues:

1. Code style:

```
  main.tf:364:83: warning: List items should be accessed using square brackets ()
```
https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/actions/runs/5179362958/jobs/9332797160?pr=204#step:6:120

2. Update README by running
```
README.md is outdated. Please run the following commands locally and push the file:
  make init
  make readme
```

https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/actions/runs/5179362958/jobs/9332793659?pr=204

Thanks.

**Comment by mightyguava** [comment]
hey @goruha i'm happy to fix the lint issue, but wanted to double-check that it won't break any backwards compatibility contract the module has? The lint is complaining about `"${join("", aws_ecs_task_definition.default.*.family)}:${join("", aws_ecs_task_definition.default.*.revision)}"` matches the original code on `main`.

**Comment by goruha** [comment]
@mightyguava 
I checked tflint log again.

It failed because of runs out of warning limits.
All warnings are about list items' access

`aws_ecs_task_definition.default.*.family` should be `aws_ecs_task_definition.default[*].family`

Could you fix all of them? 

[]  main.tf:364:40: warning: List items should be accessed using square brackets ()
[]  main.tf:364:83: warning: List items should be accessed using square brackets ()
[]  main.tf:364:137: warning: List items should be accessed using square brackets ()
[]  main.tf:463:40: warning: List items should be accessed using square brackets ()
[]  main.tf:463:83: warning: List items should be accessed using square brackets ()
[]  main.tf:463:137: warning: List items should be accessed using square brackets ()
[]  main.tf:562:40: warning: List items should be accessed using square brackets ()
[]  main.tf:562:83: warning: List items should be accessed using square brackets ()
[]  main.tf:562:137: warning: List items should be accessed using square brackets ()
[]  main.tf:661:40: warning: List items should be accessed using square brackets ()
[]  main.tf:661:83: warning: List items should be accessed using square brackets ()
[]  main.tf:661:137: warning: List items should be accessed using square brackets ()

**Comment by mightyguava** [comment]
Done!

**Comment by goruha** [comment]
@mightyguava Thanks for your contribution. 

LGTM

**Review by goruha — APPROVED** [review]

**Pull request merged**
