### PR TITLE
Fix service naming

### PR DESCRIPTION
**Pull request by ragumix**
## what
* Fix naming for ECS service

## why
* Change naming for ECS service due to it's clear that for example service connects to **trunk/preprod/prod** environment by the belonging to the corresponding ECS cluster. It's redundantly to use environment or other labels in the name of the service. It can be just simply ***service1, service2, etc.*** instead of ***trunk-service1, trunk-service2, etc.***
* Also service name is not a unique within the region and is connected to the corresponding ECS cluster, so that's why can be the same naming for services in different clusters.

### CODE REVIEW

**Comment by ragumix** [comment]
@joe-niland yes, I know about **label_order** parameter. But if you specify **label_order = ["name"]**, then not only service_name will be just simply _name_, but others resources too (IAM roles, task definition, etc.). Some of these resources have to have a unique name within the account.
In my case we have several environments (trunk, preprod) in one AWS account and it needs to have unique names for such resources like IAM roles, then we can't just specify **label_order = ["name"]** and we use other environment attributes in label_order. But in our case we would want to have not overloaded and complex names for ecs services. That's why I suggested this PR. Hope it helped to understand use case when it needs.
You've already closed this PR, but if you changed your mind after my comment, please show it again.
Thanks for your work!

**Comment by Nuru** [comment]
Instead of introducing a breaking change with
```hcl
  name  = module.this.name
```

Add a new optional variable `ecs_service_name`

```hcl
variable "ecs_service_name" {
  type        = list(string)
  description = <<-EOT
    If list is not empty, use the first element as the name of the ECS service. 
    Otherwise a name will be generated.
    EOT
  default     = []
}
```

```hcl
  name = length(var.ecs_service_name) > 0 ? var.ecs_service_name[0] : module.this.id
```

**Comment by ragumix** [comment]
@Nuru yes, your solution is better.
I've fixed my PR correspondingly. But I suppose it doesn't need to have a list(string) for this new variable, so I've changed it to string.

**Comment by joe-niland** [comment]
@ragumix picking this up again.. the reason the suggested input is a list is because if the name is supplied by the output of a another module, using a list will work but using a string will cause Terraform to throw an error.

If you want to continue this PR, please make that change and also sync your branch with main.

**Comment by joe-niland** [comment]
@ragumix i'll close for now but feel free to get in touch if you want to reopen

**Pull request closed without merging**
