### PR TITLE
Update null-label to restore attribute order

### PR DESCRIPTION
**Pull request by Nuru**
## what
- Update `terraform-null-label` to restore attribute order handling in place prior to #82

## why
- Automatic merging of old attributes with new attributes was added to `terraform-null-label` v0.19.0 and incorporated into this module in #82. However, prior to `terraform-null-label` v0.22.1, it placed new attributes in front of old attributes, instead of the previous behavior of this module, which was to place new attributes at the end of the attribute list. This causes unnecessary and unwanted changes in resource names.

## references
-  cloudposse/terraform-null-label#113

### CODE REVIEW

**Comment by Nuru** [comment]
@if-igor This restores the old attribute order

**Review by mcalhoun — APPROVED** [review]
LGTM!

**Pull request merged**
