### PR TITLE
BUG | Support Dynamic deployment_circuit_breaker for CODE_DEPLOY 

### PR DESCRIPTION
**Pull request by lgants**
## what
* The `deployment_circuit_breaker` option is now a dynamic block with a conditional for the `deployment_controller_type` value

## why
* This PR fixes an issue when using `CODE_DEPLOY` `deployment_circuit_breaker` option. 
* Previously, the `deployment_circuit_breaker` was always included as part of the module. However, the [AWS DeploymentCircuitBreaker documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentCircuitBreaker.html) states":

> The deployment circuit breaker can only be used for services using the rolling update (ECS) deployment type that aren't behind a Classic Load Balancer.

Consequently, when using `CODE_DEPLOY` for `deployment_circuit_breaker` with this module, the state is consistently out of sync with the remote, which attempts to sync with the remote on every update.
 
Screen Shot 2022-06-25 at 2 00 55 PM

## references
* AWS DeploymentCircuitBreaker documentation: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentCircuitBreaker.html

### CODE REVIEW

**Comment by lgants** [comment]
Any updates on this? Would love to get back to 0 updates on apply soon. 😁

Let me know if you need any changes.

**Review by joe-niland — APPROVED** [review]

**Comment by joe-niland** [comment]
@lgants thanks for bumping and for your contribution! Released as https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/releases/tag/0.65.0

**Comment by lgants** [comment]
Awesome! Thanks @joe-niland both for merging and for all you do to support cloudposse's top-notch open-source code

**Pull request merged**
