### PR TITLE
fix: create task definition before destroying the existing one

### PR DESCRIPTION
**Pull request by syphernl**
## what
* Added `create_before_destroy` to the task definition

## why
* Currently, when applying the state fails you will be left out with a task definition

### CODE REVIEW

**Comment by nitrocode** [comment]
hi @syphernl. Thanks for the contribution. We're still waiting for the new sg module 0.4.0 to be used with this repo before this repos code is unfrozen. Please wait for us to complete that before we merge this pr.

**Comment by Nuru** [comment]
@nitrocode @aknysh `create_before_destroy` is a breaking change. It can be folded into the Security Group 0.4.0 upgrade, but please assess the cost/benefit of the change before introducing it, and provide a migration strategy suitable for a live production environment.

**Comment by syphernl** [comment]
@nitrocode @Nuru Any updates on this one?

**Pull request closed without merging**
